// company_data.dart

final Map<String, String> companyCodeMap = {
  "Abans Electricals PLC": "ABAN.N0000",
  "Abans Finance PLC": "AFSL.N0000",
  "Access Engineering PLC": "AEL.N0000",
  "ACL Cables PLC": "ACL.N0000",
  "ACL Plastics PLC": "APLA.N0000",
  "ACME Printing & Packaging PLC": "ACME.N0000",
  "Agalawatte Plantations PLC": "AGAL.N0000",
  "Agarapatana Plantations PLC": "AGPL.N0000",
  "Agstar PLC": "AGST.N0000",
  "Aitken Spence Hotel Holdings PLC": "AHUN.N0000",
  "Aitken Spence Plantation Managements PLC": "ASPM.N0000",
  "Aitken Spence PLC": "SPEN.N0000",
  "Alliance Finance Company PLC": "ALLI.N0000",
  "Alpha Fire Services PLC": "AFS.N0000",
  "Alumex PLC": "ALUM.N0000",
  "Amana Bank PLC": "ABL.N0000",
  "Amana Takaful PLC": "ATL.N0000",
  "Amana Takaful Life PLC": "ATLL.N0000",
  "Ambeon Capital PLC": "TAP.N0000",
  "Ambeon Holdings PLC": "GREG.N0000",
  "AMW Capital Leasing & Finance PLC": "AMCL.N0000",
  "Arpico Insurance PLC": "AINS.N0000",
  "Asia Asset Finance PLC": "AAF.N0000",
  "Asia Capital PLC": "ACAP.N0000",
  "Asia Siyaka Commodities Limited": "ASIY.N0000",
  "Asian Hotels & Properties PLC": "AHPL.N0000",
  "Asiri Hospital Holdings PLC": "ASIR.N0000",
  "Asiri Surgical Hospital PLC": "AMSL.N0000",
  "Associated Motor Finance Company PLC": "AMF.N0000",
  "B P P L Holdings PLC": "BPPL.N0000",
  "Bairaha Farms PLC": "BFL.N0000",
  "Balangoda Plantations PLC": "BALA.N0000",
  "Bansei Royal Resorts Hikkaduwa PLC": "BRR.N0000",
  "Beruwala Resorts PLC": "BERU.N0000",
  "Bogala Graphite Lanka PLC": "BOGA.N0000",
  "Bogawantalawa Tea Estates PLC": "BOPL.N0000",
  "Brown & Company PLC": "BRWN.N0000",
  "Browns Beach Hotels PLC": "BBH.N0000",
  "Browns Investments PLC": "BIL.N0000",
  "Bukit Darah PLC": "BUKI.N0000",
  // ignore: equal_keys_in_map
  "Brown & Company PLC": "BRWN.N0000",
  "C T Holdings PLC": "CTHR.N0000",
  "Cargills (Ceylon) PLC": "CARG.N0000",
  "Chevron Lubricants Lanka PLC": "LLUB.N0000",
  "Ceylon Beverage Holdings PLC": "BREW.N0000",
  "Ceylon Cold Stores PLC": "CCS.N0000",
  "Ceylon Tobacco Company PLC": "CTC.N0000",
  "Commercial Bank of Ceylon PLC": "COMB.N0000",
  "Commercial Credit and Finance PLC": "COCR.N0000",
  "Commercial Development Company PLC": "COMD.N0000",
  "Dialog Axiata PLC": "DIAL.N0000",
  "Distilleries Company of Sri Lanka PLC": "DIST.N0000",
  "DFCC Bank PLC": "DFCC.N0000",
  "Digital Mobility Solutions Lanka PLC": "PKME.N0000",
  "Hatton National Bank PLC": "HNB.N0000",
  "Hayleys PLC": "HAYL.N0000",
  "Hayleys Fabric PLC": "HAYF.N0000",
  "Hemas Holdings PLC": "HEMAS.N0000",
  "Hemas Pharmaceuticals PLC": "HEMP.N0000",
  "John Keells Holdings PLC": "JKH.N0000",
  "John Keells Hotels PLC": "JKH.X0000",
  "Lanka IOC PLC": "LIOC.N0000",
  "LB Finance PLC": "LBFIN.N0000",
  "LOLC Finance PLC": "LOFC.N0000",
  "LOLC Holdings PLC": "LOLC.N0000",
  "Melstacorp PLC": "MELS.N0000",
  "National Development Bank PLC": "NDB.N0000",
  "Nations Trust Bank PLC": "NTB.N0000",
  "Nestlé Lanka PLC": "NEST.N0000",
  "Overseas Realty (Ceylon) PLC": "ORCL.N0000",
  "PGP Glass Ceylon PLC": "PGGL.N0000",
  "Richard Pieris & Company PLC": "RICH.N0000",
  "Royal Ceramics Lanka PLC": "ROSE.N0000",
  "Sampath Bank PLC": "SAMP.N0000",
  "Seylan Bank PLC": "SEYB.N0000",
  "Softlogic Life Insurance PLC": "SOFT.N0000",
  "Sri Lanka Telecom PLC": "SLTL.N0000",
  "Sunshine Holdings PLC": "SUN.N0000",
  "Teejay Lanka PLC": "TJL.N0000",
  "Union Assurance PLC": "UAL.N0000",
  "Vallibel One PLC": "VONE.N0000",
  "Vallibel Finance PLC": "VFIN.N0000",
  "WindForce PLC": "WIND.N0000",
  "Waskaduwa Beach Resort & Spa PLC": "WASK.N0000"
};
